let nightclick=true;
function night(){
  if(nightclick){

    document.querySelector(
      "body"
    ).style.color="white";
    document.querySelector(
      "body"
    ).style.backgroundColor="black";
    document.querySelector(
      ".container"
    ).style.backgroundColor="whitesmoke";
    document.querySelector(
      ".spp"
    ).style.color="black";
    document.querySelector(
      ".spp"
    ).style.fontWeight="bolder";
    document.querySelector(
      ".spp1"
    ).style.color="black";
    document.querySelector(
      ".spp1"
    ).style.fontWeight="bolder";
    document.querySelector(
      ".spp2"
    ).style.color="black";
    document.querySelector(
      ".spp2"
    ).style.fontWeight="bolder";
    document.querySelector(
      ".spp3"
    ).style.color="black";
    document.querySelector(
      ".spp3"
    ).style.fontWeight="bolder";
    document.querySelector(
      ".dig"
    ).style.color="black";
    document.querySelector(
      ".container"
    ).style.borderRadius="10px";
    document.querySelector(
      ".main"
    ).style.boxshadow="2px 2px 12px white";
    document.querySelector(
      ".row"
    ).style.backgroundColor="black";
    document.querySelector(
      ".night"
    ).style.backgroundImage="url(ind-img/cab2.png)";
    document.querySelector(
      ".night"
    ).style.backgroundColor="white";
    document.querySelector(
      ".night"
    ).style.borderRadius="8px";
    document.querySelector(
      ".night"
    ).style.marginRight="5px";
    document.querySelector(
      ".ride_text"
    ).style.color="white";
    document.querySelector(
      ".bol"
    ).style.color="white";
    document.querySelector(
      ".cabe_text"
    ).style.color="white";
    document.querySelector(
      ".secure_text"
    ).style.color="white";
    document.querySelector(
      ".cabb"
    ).style.color="white";
    document.querySelector(
      ".cabb2"
    ).style.color="white";
    document.querySelector(
      ".head"
    ).style.color="white";
    document.querySelector(
      ".head1"
    ).style.color="white";
    document.querySelector(
      ".head2"
    ).style.color="white";
    document.querySelector(
      ".head3"
    ).style.color="white";
    document.querySelector(
      ".head4"
    ).style.color="white";
    document.querySelector(
      ".bg_color"
    ).style.backgroundColor="black";
    document.querySelector(
      ".bg_color"
    ).style.color="white";
    document.querySelector(
      ".nation"
    ).style.color="white";
    document.querySelector(
      ".t_color"
    ).style.color="white";
    document.querySelector(
      ".btn"
    ).style.backgroundColor="white";
    document.querySelector(
      ".btn"
    ).style.color="black";
    document.querySelector(
      ".btn"
    ).style.fontWeight="bolder";
    document.querySelector(
      ".a1"
    ).style.color="white";
    document.querySelector(
      ".a1"
    ).style.fontWeight="bolder";
    document.querySelector(
      ".a2"
    ).style.color="white";
    document.querySelector(
      ".a2"
    ).style.fontWeight="bolder";
    document.querySelector(
      ".a3"
    ).style.color="black";
    document.querySelector(
      ".a3"
    ).style.fontWeight="bolder";
    document.querySelector(
      ".arr-img"
    ).style.backgroundImage="url(ind-img/down-arr-w.jpg)";
    document.querySelector(
      ".img1"
    ).style.backgroundImage="url(ind-img/delivery-man-w.png)";
    document.querySelector(
      ".img2"
    ).style.backgroundImage="url(ind-img/airplane-w.png)";
    document.querySelector(
      ".img3"
    ).style.backgroundImage="url(ind-img/backpack-w.png)";
  nightclick=false;
  }
  else{

    document.querySelector(
      "body"
    ).style.color="";
    document.querySelector(
      "body"
    ).style.backgroundColor="";
    document.querySelector(
      ".container"
    ).style.backgroundColor="";
    document.querySelector(
      ".spp"
    ).style.color="";
    document.querySelector(
      ".spp"
    ).style.fontWeight="";
    document.querySelector(
      ".spp1"
    ).style.color="";
    document.querySelector(
      ".spp1"
    ).style.fontWeight="";
    document.querySelector(
      ".spp2"
    ).style.color="";
    document.querySelector(
      ".spp2"
    ).style.fontWeight="";
    document.querySelector(
      ".spp3"
    ).style.color="";
    document.querySelector(
      ".spp3"
    ).style.fontWeight="";
    document.querySelector(
      ".dig"
    ).style.color="white";
    document.querySelector(
      ".container"
    ).style.borderRadius="";
    document.querySelector(
      ".main"
    ).style.boxshadow="";
    document.querySelector(
      ".row"
    ).style.backgroundColor="";
    document.querySelector(
      ".night"
    ).style.backgroundImage="";
    document.querySelector(
      ".night"
    ).style.backgroundColor="";
    document.querySelector(
      ".night"
    ).style.borderRadius="";
    document.querySelector(
      ".night"
    ).style.marginRight="";
    document.querySelector(
      ".ride_text"
    ).style.color="";
    document.querySelector(
      ".bol"
    ).style.color="";
    document.querySelector(
      ".cabe_text"
    ).style.color="";
    document.querySelector(
      ".secure_text"
    ).style.color="";
    document.querySelector(
      ".cabb"
    ).style.color="";
    document.querySelector(
      ".cabb2"
    ).style.color="";
    document.querySelector(
      ".head"
    ).style.color="";
    document.querySelector(
      ".head1"
    ).style.color="";
    document.querySelector(
      ".head2"
    ).style.color="";
    document.querySelector(
      ".head3"
    ).style.color="";
    document.querySelector(
      ".head4"
    ).style.color="";
    document.querySelector(
      ".bg_color"
    ).style.backgroundColor="";
    document.querySelector(
      ".bg_color"
    ).style.color="";
    document.querySelector(
      ".nation"
    ).style.color="";
    document.querySelector(
      ".t_color"
    ).style.color="";
    document.querySelector(
      ".btn"
    ).style.backgroundColor="";
    document.querySelector(
      ".btn"
    ).style.color="";
    document.querySelector(
      ".btn"
    ).style.fontWeight="";
    document.querySelector(
      ".a1"
    ).style.color="";
    document.querySelector(
      ".a1"
    ).style.fontWeight="";
    document.querySelector(
      ".a2"
    ).style.color="";
    document.querySelector(
      ".a2"
    ).style.fontWeight="";
    document.querySelector(
      ".a3"
    ).style.color="";
    document.querySelector(
      ".a3"
    ).style.fontWeight="";
    document.querySelector(
      ".arr-img"
    ).style.backgroundImage="";
    document.querySelector(
      ".img1"
    ).style.backgroundImage="";
    document.querySelector(
      ".img2"
    ).style.backgroundImage="";
    document.querySelector(
      ".img3"
    ).style.backgroundImage="";

    nightclick=true;
  }
}
function redirectToRates(){
  document.querySelector(
    ".rates"
  ).style.display="flex";
  
  let vv=randomNumber();
  document.querySelector(
    ".tret"
  ).value=vv;
  document.querySelector(
    ".tret1"
  ).value=vv*1.5;
  document.querySelector(
    ".tret2"
  ).value=vv*0.8;
}
function randomNumber() {
  return Math.floor(Math.random()* 20 + 10);
}